### ISSUE TITLE
Use multiple samples to compute the color

### ISSUE THREAD

**Issue by gbip** [gbip/tcs3200#1]
Since the color sensor might not be very precise, using multiple samples to compute the color value would be a good idea.
The idea would be to add a new argument to [`hz_To_Color`](https://github.com/gbip/tcs3200/blob/master/src/lib.rs#L49) which represent the number of sample to take.
Then we could average those samples and return the result.
@Manah7 @christalecrouard do you feel capable of doing this ?

**Comment by Manah7** [comment]
Done, I added 'nb_pass' to hz_To_color which now returns an average of the readings.
