### ISSUE TITLE
Run clippy on the code

### ISSUE THREAD

**Issue by gbip** [gbip/tcs3200#2]
In order to release a library into the wild, it is good practice to verify that it meets some [basic guidelines](https://rust-lang-nursery.github.io/api-guidelines/).
The first step is to clean up the code, and to follow the naming conventions of the language.
Then it would be a good idea to [run clippy](https://github.com/rust-lang/rust-clippy) on the code.

**Comment by Manah7** [comment]
Code cleaned with Clippy.
